### ISSUE TITLE
Tap 문의와 Customentity 문의

### ISSUE THREAD

**Issue by jini5012** [patrick-mc/hyper-core-game#1]
제가 커스텀 엔티티와 Tap을 jar로 컴파일해서
서버에다가 slow fps 플러그인도 넣고 hypercore도 넣는데 tap과 customentity는 
plugin.yml이 있으몀 안된다고 해서 plugin.yml을 지우고 다시컴파일해도 똑같은 오류가 나서
어떻게 해야 돼는지 모르겠네요

**Comment by jini5012** [comment]
아 slow fps도 그렇네요

**Comment by patrick-mc** [comment]
어떻게 컴파일을 하셨는지는 모르겠지만 오류 로그 첩부해주시면 감사하겠습니다. Hypercore는 개발 하다가 잠시 쉬고 있는 프로젝트이며, 클라이언트 사이드에 커스텀 엔티티 모드가 필요합니다. 따라서 정상적인 실행이 힘들 가능성이 큽니다.

**Comment by jini5012** [comment]
저는 그때 당시 gradlew clean jar로 밖에 컴파일을 하지못해서
gradlew clean jar로 컴파일해서 tap과 custom entity와 slowfps는 jar 형태로 컴파일이 됐고
hypercore는 distjar로 컴파일해서 문제는 없는데
hypercore는 Tap과 customEntity가 없어서 적용이 안돼고 있습니다
hypercore는 hyper-core-game-0.3-beta-dist.jar
slowfps는 초반부터 안됐고요
오류로그




Tap 오류로그: Could not load 'plugins\tap-1.0.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more




customentity오류로그:Could not load 'plugins\custom-entity-bukkit-1.0.3.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Tap
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]


hypercore오류로그:Could not load 'plugins\hyper-core-game-0.3-beta-dist.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Tap
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]

**Comment by patrick-mc** [comment]
Hyper은 아직 문제가 많아서 사용하기를 권장드리지는 못하고, 오류 로그를 보니.tap의 plugin.yml 파일이 없다고 하네요. Tap의 문제일 가능성이 크니, 다시 빌드해보시는 것을 권장드립니다.

**Comment by patrick-mc** [comment]
Custom entity 자체가 클라이언트 측 모드가 필요해서 아마 빌드하시더라도 사용이 불가능할 수도 있을겁니다...

**Comment by jini5012** [comment]
Patrick-mc님 원래 custom entity forge가 있지 않았나요?

**Comment by patrick-mc** [comment]
> Patrick-mc님 원래 custom entity forge가 있지 않았나요?

제가 만든 플러그인이 아닌 noonmaru님께서 만드신 nemosource에 올라와있던 custom-entity-mod를 수정해서 올린 것이였으며, 저작권에 맞지 않다고 판단하여, 레포지토리를 삭제했습니다. 안정적이지 못한 코드이기 때문에 이전에 받으셨더라도 사용을 권장드리지 않습니다..

**Comment by jini5012** [comment]
그러면 slow fps를 즐긴 서버가 있나요?

**Comment by jini5012** [comment]
제가 tap을 수정해서 해도 안되네요

**Comment by jini5012** [comment]
slow fps를 즐긴 서버가 있으면 주시기를 원해요.

**Comment by patrick-mc** [comment]
> slow fps를 즐긴 서버가 있으면 주시기를 원해요.

제 컴퓨터가 이틀 전에 날아가서 모든 자료를 소실했습니다(모든 서버/소스/자료/모드)...
tap은 noonmaru님의 1.0.1 빌드를 받아서 spigotJar로 빌드하시면 될 것 같네요.. (디렉토리만 변경하시면 될겁니다)
slowfps는 tap만 정상 작동한다면, 플레이에 문제 없을 것 같습니다.
추가 문제 없으면 close 해주시면 감사하겠습니다

**Comment by jini5012** [comment]
다시 빌드를 했는데
똑같은 오류가 나네요

**Comment by jini5012** [comment]
디렉토리만 바꿨는데 똑같은 오류가 나요

**Comment by jini5012** [comment]
tap과 custom entity를 빌드해서 주실수 있으시면 zip file로 해서 이메일로 보내주세요
이메일:wjkong09@gmail.com

**Comment by jini5012** [comment]
tap은 1.0,1.0.1둘 다 보내주시면 감사하고 CUSTOM ENTITY도 1.0,1.0.1,1.0.2,1.0.3넷 다 보내주시면 감사하겠습니다

**Comment by patrick-mc** [comment]
커스텀 엔티티는 최신 1.0.3만 있어도 플레이에 문제 없습니다. 컴퓨터 복구되는대로 tap, customentity 빌드해보겠습니다.

**Comment by jini5012** [comment]
네 감사합니다

**Comment by jini5012** [comment]
그냥 넷다 보내주세요

**Comment by jini5012** [comment]
되시면 모드도 주세요(커스텀 엔티티)
