### ISSUE TITLE
서버 오류

### ISSUE THREAD

**Issue by jini5012** [patrick-mc/hyper-core-game#3]
어제는 플러그인 만들다가 오류나더니 이제는 서버 오류가 나네요.하..난 오류맨인가?

오류로그:Error occurred while enabling HyperCore v0.3-beta (Is it up to date?)
java.lang.NoClassDefFoundError: com/github/patrick/utils/bukkit/BukkitClassLoader
        at com.github.patrick.hypercore.Hyper.<clinit>(Hyper.kt:33) ~[?:?]
        at com.github.patrick.hypercore.plugin.HyperCorePlugin.onEnable(HyperCorePlugin.kt:33) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: com.github.patrick.utils.bukkit.BukkitClassLoader
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_241]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2cf50f0-2b93d83]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        ... 13 more

**Comment by jini5012** [comment]
으아아아아아아아아아아아아아아아아아

**Comment by patrick-mc** [comment]
오류 해결되었을겁니다. 감사합니다.
